;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        bm-toggle
        c-electric-delete-forward
        crux-eval-and-replace
        dabbrev-expand
        dired-do-flagged-delete
        dired-flag-file-deletion
        electric-newline-and-maybe-indent
        end-of-buffer
        forward-sexp
        hydra--negative-argument
        ignore
        indent-for-tab-command
        kill-region
        nxml-electric-slash
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-insert-heading-respect-content
        org-kill-line
        org-open-line
        org-self-insert-command
        org-todo
        paredit-backward
        paredit-forward
        paredit-forward-delete
        paredit-kill
        paredit-open-round
        replace-last-sexp
        swiper
        transpose-words
        yaml-electric-dash-and-dot
        zap-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        counsel-M-x
        hydra--digit-argument
        mc-hydra/body
        mc-hydra/mc/mark-next-like-this
        mc-hydra/mc/mark-next-lines
        mc-hydra/mc/mark-previous-like-this
        mc-hydra/mc/mark-previous-lines
        mc-hydra/nil
        paredit-backslash
        swiper
        text-scale-adjust
        yaml-electric-backspace
        ))
